### PR TITLE
Add share on mastodon option

### LINKED ISSUE #45: Add "Share to Mastodon" button
Add a "Share to Mastodon" button to the existing share toolbar underneath blog posts. 

[This guide](https://www.kylereddoch.me/2023/02/20/creating-mastodon-share-button.html) may be helpful.

### PR DESCRIPTION
**Pull request by devmount**
This change uses a web component to offer a share icon for Mastodon instances. It also fixes icon wrapping on narrow viewports.

image

Closes #45

### CODE REVIEW

**Comment by MelissaAutumn** [comment]
Aside from my comment on the issue about pulling the script into our repo, this looks good! I'll test it on Monday, and do the release tagging when the pr is merged.

Thanks!

**Comment by devmount** [comment]
Thank you Mel! I moved Micahs component to a local asset now. I also added some credits to the head of the web components file:

```js
/**
 * @author Micah Ilbery
 * @version 1.1.0
 * @license GPL-3.0
 * @url https://github.com/micahilbery/share-on-mastodon
 */
```

@micahilbery I hope it's ok for you like this.

**Comment by MelissaAutumn** [comment]
Working great. Can we minify the file? Once that's done this is good to get merged.

**Comment by devmount** [comment]
Of course, I added a minified version and included that instead.

**Comment by MelissaAutumn** [comment]
Thanks a bunch!

**Pull request merged**
